# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_myAI_GUI(object):
    def setupUi(self, myAI_GUI):
        myAI_GUI.setObjectName("myAI_GUI")
        myAI_GUI.resize(1800,1800)
        self.centralwidget = QtWidgets.QWidget(myAI_GUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -20, 1800, 1800))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/aig.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1500,800, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(150, 204, 237), stop:1 rgb(#f3f6f8));\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1500,900, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(150, 204, 237), stop:1 rgb(#f3f6f8));\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 491, 211))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/init.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(390, 50, 121, 31))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(520, 50, 121, 31))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        myAI_GUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(myAI_GUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 22))
        self.menubar.setObjectName("menubar")
        myAI_GUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(myAI_GUI)
        self.statusbar.setObjectName("statusbar")
        myAI_GUI.setStatusBar(self.statusbar)

        self.retranslateUi(myAI_GUI)
        QtCore.QMetaObject.connectSlotsByName(myAI_GUI)

    def retranslateUi(self, myAI_GUI):
        _translate = QtCore.QCoreApplication.translate
        myAI_GUI.setWindowTitle(_translate("myAI_GUI", "MainWindow"))
        self.pushButton.setText(_translate("myAI_GUI", "RUN"))
        self.pushButton_2.setText(_translate("myAI_GUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    myAI_GUI = QtWidgets.QMainWindow()
    ui = Ui_myAI_GUI()
    ui.setupUi(myAI_GUI)
    myAI_GUI.show()
    sys.exit(app.exec_())
